### PR TITLE
chore: (#1278) Removing utils folder

### LINKED ISSUE #1278: There shouldn't be 'Utils' package containing business logic
https://github.com/trustbloc/wallet/tree/main/cmd/wallet-web/src/utils

move mixins pkg to root in parallel to pages if not inside and move i18n inside mixins

### PR DESCRIPTION
**Pull request by victro**
closes #1278

### CODE REVIEW

**Review by birtony — APPROVED** [review]

**Comment by birtony** [comment]
Let's squash your commits and sign them. You'd basically need to do `commit -s -m "semver commit message"` to sign your commits. You can also setup `GPG Keychain` to avoid having to enter a passphrase each time you try to make a signed commit. Otherwise looks good!

**Comment by rolsonquadras** [comment]
@cla-bot check

**Comment by rolsonquadras** [comment]
@victro You can refer https://www.conventionalcommits.org/en/v1.0.0/#summary for semantic pull request title (possible values - https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum)

**Review by rolsonquadras — APPROVED** [review]

**Comment by talwinder50** [comment]
You can remove issue number from the pr description

**Pull request merged**
