### PR TITLE
feat: implemented credential details banner component

### LINKED ISSUE #1028: Implement reusable component for credential details banner, design refinements

### PR DESCRIPTION
**Pull request by birtony**
Fixes #1028

image
image
image
image
image

Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>

### CODE REVIEW

**Review by rolsonquadras — APPROVED** [review]

**Comment by talwinder50** [comment]
Please add the screenshot

**Comment by birtony** [comment]
> Please add the screenshot

Added. FYI, mobile design will be tackled in a separate issue @talwinder50

**Comment by talwinder50** [comment]
Also the banner values need to be extracted from vc in the helper.js file. Will you do that in separate pr ??

**Comment by talwinder50** [comment]
Yes its fine desktop is the priority first.

**Comment by birtony** [comment]
> Also the banner values need to be extracted from vc in the helper.js file. Will you do that in separate pr ??

Yes, will add later

**Review by talwinder50 — APPROVED** [review]

**Pull request merged**
