### PR TITLE
chore: update latest afgo and agent-sdk

### PR DESCRIPTION
**Pull request by Baha-sk**
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

### CODE REVIEW

**Review by birtony — COMMENTED** [review]
I am wondering why so many `.vue` files got linted?

**Comment by Baha-sk** [comment]
> I am wondering why so many `.vue` files got linted?

it's probably triggered by the build?

**Comment by birtony** [comment]
> > I am wondering why so many `.vue` files got linted?
> 
> it's probably triggered by the build?

Might've been that you didn't run `npm i` in the root and `prettier` did not run...I'll files an issue to investigate more

**Review by birtony — APPROVED** [review]

**Comment by Baha-sk** [comment]
> > > I am wondering why so many `.vue` files got linted?
> > 
> > 
> > it's probably triggered by the build?
> 
> Might've been that you didn't run `npm i` in the root and `prettier` did not run...I'll files an issue to investigate more

I only ran `make all`, nothing else

**Review by fqutishat — APPROVED** [review]

**Pull request merged**
